#ifndef PROGRAMMATION_DYNAMIQUE_FUNCTION_H
#define PROGRAMMATION_DYNAMIQUE_FUNCTION_H

#define ARRAY_MAX_SIZE 1000
#define ARRAY_VALUE_RESEARCHED 630

void testDychotomy(void);
void testKnapsack(void);
void testPGCB(void);

#endif //PROGRAMMATION_DYNAMIQUE_FUNCTION_H